### ISSUE TITLE
Running pip install upgrades django to 1.4

### ISSUE THREAD

**Issue by andybak** [benjaoming/django-relatedadminwidget#1]
Which wasn't what I wanted on my nice Django 1.3 project.

**Comment by benjaoming** [comment]
Hi can you test if it works now? I have changed the dependency to django 1.3 but I haven't tested it.

d594393a0f9ad1801469d8cf0aa50bc94ad1c55f

**Comment by andybak** [comment]
My point was that it shouldn't have Django as a dependency, should it?

No-one is going to install this unless they are already have Django installed.

**Comment by benjaoming** [comment]
It won't work on any django version... check the source code. I'm not sure, but I think it breaks on 1.2 -- and it might break in 1.5, so that would just produce a dependency that said django>=1.3 and django<1.5 -- this is normal to state in any django app.

**Comment by wardk** [comment]
Django got upgraded from 1.7 to 1.7.1 with me. I agree with andybak: it's not what you expect. Unless all django addons do this, i think it's better to drop the django dependency.

**Comment by benjaoming** [comment]
You have probably been running `pip install django-relatedadminwidget --upgrade` ? You should ask pip explicitly to not try to update django in this circumstance. I mean, I could completely remove the Django dependency, but that would also remove the requirement of Django>=1.3.. this is common practice.

To upgrade without upgrading django, you can run `pip install django-relatedadminwidget django\<=1.7 --upgrade`
