### ISSUE TITLE
replace .live by .on in jquery

### ISSUE THREAD

**Issue by wardk** [benjaoming/django-relatedadminwidget#6]
Deprecated 'live' function (http://api.jquery.com/live/) in relatedwidget.js caused javascript error, breaking the grappelli interface i'm using. I understand it's a jquery version issue. It could solve it quite easily by replacing the two live() function calls on lines 36 and 48 by on()

**Comment by benjaoming** [comment]
Acknowledged, can you make a PR for that? :) I'll make sure to release an update on pypi after.

**Comment by wardk** [comment]
Not familiar with github, sry. While trying to create the PR, i found that joelcrocker already made the edit a year ago. I installed with pip, few months ago, guess that package was outdated.

**Comment by benjaoming** [comment]
Oh cool, I didn't know! Can you test the latest 0.0.3 release and see if it works? I've put it on PyPi so you can `pip install django-relatedadminwidget` -- setup.py produces some warnings, but shouldn't matter...

**Comment by wardk** [comment]
Did a pip3 install -U django-relatedadminwidget; files are updated and everything seems to work fine.

**Comment by benjaoming** [comment]
Great! But wait, you're running python3? Does it work with python3?? :)

**Comment by wardk** [comment]
Yup, i'm thinking you weren't specifically aiming for it? Given that it's mostly JavaScript and template, and django not being any different, i guess there's no reason why it wouldn't work... Anyway, it's mighty useful, i can't understand why it's not in the default admin or at least in grappelli.

**Comment by benjaoming** [comment]
Yeah, normally having python3 support only happens on purpose :) Thanks :)

Neither do I understand why it's absent in even Grappelli and django-suit.. but let's keep this project alive as long as needed.
